name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os  }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2019]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package

      - name: Upload result job ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: target/**/*.{AppImage,dmg,exe}
          compression-level: 0
          overwrite: false

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: target/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: target/**/*
